import test from "node:test";
import assert from "node:assert/strict";
import {
  commandLooksLikeBroadTestCommand,
  commandLooksLikeFocusedTestCommand,
  commandLooksLikeLocalValidationCommand,
  commandLooksLikeTestCommand,
  normalizeCommand
} from "../src/commands/classify";

test("review-surfaces.COLLECTOR.7 classifies broad and focused test commands", () => {
  assert.equal(normalizeCommand(" pnpm   run   test:fast "), "pnpm run test:fast");
  assert.equal(commandLooksLikeTestCommand("pnpm run test:fast"), true);
  assert.equal(commandLooksLikeBroadTestCommand("pnpm run test:fast"), true);
  assert.equal(commandLooksLikeFocusedTestCommand("pnpm run test:fast"), false);
  assert.equal(commandLooksLikeTestCommand("pnpm run --if-present test"), true);
  assert.equal(commandLooksLikeBroadTestCommand("pnpm run --if-present test"), true);
  assert.equal(commandLooksLikeFocusedTestCommand("pnpm run --if-present test"), false);
  assert.equal(commandLooksLikeTestCommand("pnpm run --if-present test:privacy"), true);
  assert.equal(commandLooksLikeBroadTestCommand("pnpm run --if-present test:privacy"), false);
  assert.equal(commandLooksLikeFocusedTestCommand("pnpm run --if-present test:privacy"), true);
  assert.equal(commandLooksLikeTestCommand("CI=1 pnpm run test"), true);
  assert.equal(commandLooksLikeBroadTestCommand("CI=1 pnpm run test"), true);
  assert.equal(commandLooksLikeFocusedTestCommand("CI=1 pnpm run test"), false);
  assert.equal(commandLooksLikeTestCommand("NODE_OPTIONS=--conditions=test node --test dist/tests/*.test.js"), true);
  assert.equal(commandLooksLikeBroadTestCommand("NODE_OPTIONS=--conditions=test node --test dist/tests/*.test.js"), true);
  assert.equal(commandLooksLikeFocusedTestCommand("NODE_OPTIONS=--conditions=test node --test dist/tests/*.test.js"), false);
  assert.equal(commandLooksLikeTestCommand("NODE_OPTIONS='--conditions=test --import=tsx' node --test dist/tests/*.test.js"), true);
  assert.equal(commandLooksLikeBroadTestCommand("NODE_OPTIONS='--conditions=test --import=tsx' node --test dist/tests/*.test.js"), true);
  assert.equal(commandLooksLikeFocusedTestCommand("NODE_OPTIONS='--conditions=test --import=tsx' node --test dist/tests/*.test.js"), false);
  assert.equal(commandLooksLikeTestCommand("pnpm run test -- --config tests/jest.config.js"), true);
  assert.equal(commandLooksLikeBroadTestCommand("pnpm run test -- --config tests/jest.config.js"), true);
  assert.equal(commandLooksLikeFocusedTestCommand("pnpm run test -- --config tests/jest.config.js"), false);
  assert.equal(commandLooksLikeBroadTestCommand("pnpm run test:cov"), true);
  assert.equal(commandLooksLikeFocusedTestCommand("pnpm run test:cov"), false);
  assert.equal(commandLooksLikeTestCommand("pnpm run test:privacy"), true);
  assert.equal(commandLooksLikeBroadTestCommand("pnpm run test:privacy"), false);
  assert.equal(commandLooksLikeFocusedTestCommand("pnpm run test:privacy"), true);
  assert.equal(commandLooksLikeTestCommand("pnpm run test:unit:api"), true);
  assert.equal(commandLooksLikeBroadTestCommand("pnpm run test:unit:api"), false);
  assert.equal(commandLooksLikeFocusedTestCommand("pnpm run test:unit:api"), true);

  assert.equal(commandLooksLikeTestCommand("node --test dist/tests/pr-risks.test.js"), true);
  assert.equal(commandLooksLikeBroadTestCommand("node --test dist/tests/pr-risks.test.js"), false);
  assert.equal(commandLooksLikeFocusedTestCommand("node --test dist/tests/pr-risks.test.js"), true);
  assert.equal(commandLooksLikeTestCommand("node --test dist/tests/*.test.js"), true);
  assert.equal(commandLooksLikeBroadTestCommand("node --test dist/tests/*.test.js"), true);
  assert.equal(commandLooksLikeFocusedTestCommand("node --test dist/tests/*.test.js"), false);
  assert.equal(commandLooksLikeTestCommand("node --experimental-test-coverage --test dist/tests/*.test.js"), true);
  assert.equal(commandLooksLikeBroadTestCommand("node --experimental-test-coverage --test dist/tests/*.test.js"), true);
  assert.equal(commandLooksLikeFocusedTestCommand("node --import=tsx --test tests/foo.test.ts"), true);
  assert.equal(commandLooksLikeFocusedTestCommand("node --import tsx --test tests/foo.test.ts"), true);
  assert.equal(commandLooksLikeTestCommand("node --test-name-pattern risk --test dist/tests/*.test.js"), true);
  assert.equal(commandLooksLikeBroadTestCommand("node --test-name-pattern risk --test dist/tests/*.test.js"), false);
  assert.equal(commandLooksLikeFocusedTestCommand("node --test-name-pattern risk --test dist/tests/*.test.js"), true);
  assert.equal(commandLooksLikeFocusedTestCommand("node --test --test-name-pattern risk dist/tests/*.test.js"), true);
  assert.equal(commandLooksLikeTestCommand("node --test --test-shard=1/4"), true);
  assert.equal(commandLooksLikeBroadTestCommand("node --test --test-shard=1/4"), false);
  assert.equal(commandLooksLikeFocusedTestCommand("node --test --test-shard=1/4"), true);
  assert.equal(commandLooksLikeTestCommand("node --test --test-shard 1/4"), true);
  assert.equal(commandLooksLikeBroadTestCommand("node --test --test-shard 1/4"), false);
  assert.equal(commandLooksLikeFocusedTestCommand("node --test --test-shard 1/4"), true);
  assert.equal(commandLooksLikeTestCommand("node --test-shard=1/4 --test"), true);
  assert.equal(commandLooksLikeBroadTestCommand("node --test-shard=1/4 --test"), false);
  assert.equal(commandLooksLikeFocusedTestCommand("node --test-shard=1/4 --test"), true);
  assert.equal(commandLooksLikeTestCommand("node --test --test-only"), true);
  assert.equal(commandLooksLikeBroadTestCommand("node --test --test-only"), false);
  assert.equal(commandLooksLikeFocusedTestCommand("node --test --test-only"), true);
  assert.equal(commandLooksLikeTestCommand("node --test --test-skip-pattern slow"), true);
  assert.equal(commandLooksLikeBroadTestCommand("node --test --test-skip-pattern slow"), false);
  assert.equal(commandLooksLikeFocusedTestCommand("node --test --test-skip-pattern slow"), true);
  assert.equal(commandLooksLikeTestCommand("node --test-skip-pattern=slow --test"), true);
  assert.equal(commandLooksLikeBroadTestCommand("node --test-skip-pattern=slow --test"), false);
  assert.equal(commandLooksLikeFocusedTestCommand("node --test-skip-pattern=slow --test"), true);
  assert.equal(commandLooksLikeTestCommand("node --test \"**/*.test.js\""), true);
  assert.equal(commandLooksLikeBroadTestCommand("node --test \"**/*.test.js\""), true);
  assert.equal(commandLooksLikeFocusedTestCommand("node --test \"**/*.test.js\""), false);
  assert.equal(commandLooksLikeTestCommand("node --test \"test/**/*.test.js\""), true);
  assert.equal(commandLooksLikeBroadTestCommand("node --test \"test/**/*.test.js\""), true);
  assert.equal(commandLooksLikeFocusedTestCommand("node --test \"test/**/*.test.js\""), false);
  assert.equal(commandLooksLikeTestCommand("node --test --test-reporter-destination tests/results.tap"), true);
  assert.equal(commandLooksLikeBroadTestCommand("node --test --test-reporter-destination tests/results.tap"), true);
  assert.equal(commandLooksLikeFocusedTestCommand("node --test --test-reporter-destination tests/results.tap"), false);
  assert.equal(commandLooksLikeTestCommand("node --test --test-global-setup tests/setup.mjs dist/tests/*.test.js"), true);
  assert.equal(commandLooksLikeBroadTestCommand("node --test --test-global-setup tests/setup.mjs dist/tests/*.test.js"), true);
  assert.equal(commandLooksLikeFocusedTestCommand("node --test --test-global-setup tests/setup.mjs dist/tests/*.test.js"), false);
  assert.equal(commandLooksLikeFocusedTestCommand("node --test --test-reporter tap dist/tests/pr-risks.test.js"), true);
  assert.equal(commandLooksLikeBroadTestCommand("node --test --test-coverage-include src/foo.ts dist/tests/*.test.js"), true);
  assert.equal(commandLooksLikeFocusedTestCommand("node --test --test-coverage-exclude src/generated.ts dist/tests/*.test.js"), false);
  assert.equal(commandLooksLikeFocusedTestCommand("node --test 'tests/risks/*.test.js'"), true);
  assert.equal(commandLooksLikeBroadTestCommand("node --test 'tests/risks/*.test.js'"), false);
  assert.equal(commandLooksLikeFocusedTestCommand("node --test 'test/risks/*.test.js'"), true);
  assert.equal(commandLooksLikeBroadTestCommand("node --test 'test/risks/*.test.js'"), false);
  assert.equal(commandLooksLikeTestCommand("pnpm exec vitest src/risks"), true);
  assert.equal(commandLooksLikeBroadTestCommand("pnpm exec vitest src/risks"), false);
  assert.equal(commandLooksLikeFocusedTestCommand("pnpm exec vitest src/risks"), true);
  assert.equal(commandLooksLikeBroadTestCommand("pnpm exec vitest dist/tests/*.test.js"), true);
  assert.equal(commandLooksLikeFocusedTestCommand("pnpm exec vitest dist/tests/*.test.js"), false);
  assert.equal(commandLooksLikeTestCommand("pnpm exec vitest --workspace vitest.workspace.ts"), true);
  assert.equal(commandLooksLikeBroadTestCommand("pnpm exec vitest --workspace vitest.workspace.ts"), true);
  assert.equal(commandLooksLikeFocusedTestCommand("pnpm exec vitest --workspace vitest.workspace.ts"), false);
  assert.equal(commandLooksLikeBroadTestCommand("pnpm exec vitest --config src/vitest.config.ts"), true);
  assert.equal(commandLooksLikeFocusedTestCommand("pnpm exec vitest --config src/vitest.config.ts"), false);
  assert.equal(commandLooksLikeTestCommand("pnpm exec vitest --dir src/risks"), true);
  assert.equal(commandLooksLikeBroadTestCommand("pnpm exec vitest --dir src/risks"), false);
  assert.equal(commandLooksLikeFocusedTestCommand("pnpm exec vitest --dir src/risks"), true);
  assert.equal(commandLooksLikeTestCommand("pnpm exec vitest --dir=src/risks"), true);
  assert.equal(commandLooksLikeBroadTestCommand("pnpm exec vitest --dir=src/risks"), false);
  assert.equal(commandLooksLikeFocusedTestCommand("pnpm exec vitest --dir=src/risks"), true);
  assert.equal(commandLooksLikeTestCommand("pnpm exec vitest --dir=./src/risks"), true);
  assert.equal(commandLooksLikeBroadTestCommand("pnpm exec vitest --dir=./src/risks"), false);
  assert.equal(commandLooksLikeFocusedTestCommand("pnpm exec vitest --dir=./src/risks"), true);
  assert.equal(commandLooksLikeTestCommand("pnpm vitest"), true);
  assert.equal(commandLooksLikeBroadTestCommand("pnpm vitest"), true);
  assert.equal(commandLooksLikeFocusedTestCommand("pnpm vitest"), false);
  assert.equal(commandLooksLikeTestCommand("yarn vitest src/risks"), true);
  assert.equal(commandLooksLikeBroadTestCommand("yarn vitest src/risks"), false);
  assert.equal(commandLooksLikeFocusedTestCommand("yarn vitest src/risks"), true);
  assert.equal(commandLooksLikeTestCommand("pnpm exec vitest --project api"), true);
  assert.equal(commandLooksLikeBroadTestCommand("pnpm exec vitest --project api"), false);
  assert.equal(commandLooksLikeFocusedTestCommand("pnpm exec vitest --project api"), true);
  assert.equal(commandLooksLikeTestCommand("jest --selectProjects api"), true);
  assert.equal(commandLooksLikeBroadTestCommand("jest --selectProjects api"), false);
  assert.equal(commandLooksLikeFocusedTestCommand("jest --selectProjects api"), true);
  assert.equal(commandLooksLikeTestCommand("vitest --changed HEAD~1"), true);
  assert.equal(commandLooksLikeBroadTestCommand("vitest --changed HEAD~1"), false);
  assert.equal(commandLooksLikeFocusedTestCommand("vitest --changed HEAD~1"), true);
  assert.equal(commandLooksLikeTestCommand("pnpm exec vitest --changed"), true);
  assert.equal(commandLooksLikeBroadTestCommand("pnpm exec vitest --changed"), false);
  assert.equal(commandLooksLikeFocusedTestCommand("pnpm exec vitest --changed"), true);
  assert.equal(commandLooksLikeFocusedTestCommand("vitest --testNamePattern risk"), true);
  assert.equal(commandLooksLikeTestCommand("npm exec -- vitest src/risks"), true);
  assert.equal(commandLooksLikeFocusedTestCommand("npm exec -- vitest src/risks"), true);
  assert.equal(commandLooksLikeTestCommand("npm exec -- node --test dist/tests/*.test.js"), true);
  assert.equal(commandLooksLikeBroadTestCommand("npm exec -- node --test dist/tests/*.test.js"), true);
  assert.equal(commandLooksLikeFocusedTestCommand("npm exec -- node --test tests/foo.test.ts"), true);
  assert.equal(commandLooksLikeFocusedTestCommand("pnpm --filter api exec node --test dist/tests/*.test.js"), true);
  assert.equal(commandLooksLikeTestCommand("pnpm --dir services/api test"), true);
  assert.equal(commandLooksLikeBroadTestCommand("pnpm --dir services/api test"), false);
  assert.equal(commandLooksLikeFocusedTestCommand("pnpm --dir services/api test"), true);
  assert.equal(commandLooksLikeTestCommand("pnpm -C services/api test"), true);
  assert.equal(commandLooksLikeBroadTestCommand("pnpm -C services/api test"), false);
  assert.equal(commandLooksLikeFocusedTestCommand("pnpm -C services/api test"), true);
  assert.equal(commandLooksLikeTestCommand("pnpm --dir . test"), true);
  assert.equal(commandLooksLikeBroadTestCommand("pnpm --dir . test"), true);
  assert.equal(commandLooksLikeFocusedTestCommand("pnpm --dir . test"), false);
  assert.equal(commandLooksLikeTestCommand("pnpm -C ./ test"), true);
  assert.equal(commandLooksLikeBroadTestCommand("pnpm -C ./ test"), true);
  assert.equal(commandLooksLikeFocusedTestCommand("pnpm -C ./ test"), false);
  assert.equal(commandLooksLikeTestCommand("pnpm --filter api test"), true);
  assert.equal(commandLooksLikeBroadTestCommand("pnpm --filter api test"), false);
  assert.equal(commandLooksLikeFocusedTestCommand("pnpm --filter api test"), true);
  assert.equal(commandLooksLikeTestCommand("pnpm --filter api run test:fast"), true);
  assert.equal(commandLooksLikeBroadTestCommand("pnpm --filter api run test:fast"), false);
  assert.equal(commandLooksLikeFocusedTestCommand("pnpm --filter api run test:fast"), true);
  assert.equal(commandLooksLikeTestCommand("pnpm -F api exec vitest"), true);
  assert.equal(commandLooksLikeFocusedTestCommand("pnpm -F api exec vitest"), true);
  assert.equal(commandLooksLikeTestCommand("yarn workspace api test"), true);
  assert.equal(commandLooksLikeFocusedTestCommand("yarn workspace api test"), true);
  assert.equal(commandLooksLikeTestCommand("yarn workspaces foreach -A run test"), true);
  assert.equal(commandLooksLikeBroadTestCommand("yarn workspaces foreach -A run test"), true);
  assert.equal(commandLooksLikeFocusedTestCommand("yarn workspaces foreach -A run test"), false);
  assert.equal(commandLooksLikeTestCommand("yarn workspaces foreach --include @app/api run test"), true);
  assert.equal(commandLooksLikeBroadTestCommand("yarn workspaces foreach --include @app/api run test"), false);
  assert.equal(commandLooksLikeFocusedTestCommand("yarn workspaces foreach --include @app/api run test"), true);
  assert.equal(commandLooksLikeTestCommand("yarn workspaces foreach --from @app/api run test"), true);
  assert.equal(commandLooksLikeBroadTestCommand("yarn workspaces foreach --from @app/api run test"), false);
  assert.equal(commandLooksLikeFocusedTestCommand("yarn workspaces foreach --from @app/api run test"), true);
  assert.equal(commandLooksLikeTestCommand("yarn workspaces foreach --since=origin/main run test"), true);
  assert.equal(commandLooksLikeBroadTestCommand("yarn workspaces foreach --since=origin/main run test"), false);
  assert.equal(commandLooksLikeFocusedTestCommand("yarn workspaces foreach --since=origin/main run test"), true);
  assert.equal(commandLooksLikeTestCommand("yarn workspaces foreach -A run test --include @app/api"), true);
  assert.equal(commandLooksLikeBroadTestCommand("yarn workspaces foreach -A run test --include @app/api"), true);
  assert.equal(commandLooksLikeFocusedTestCommand("yarn workspaces foreach -A run test --include @app/api"), false);
  assert.equal(commandLooksLikeTestCommand("yarn workspaces run test"), true);
  assert.equal(commandLooksLikeBroadTestCommand("yarn workspaces run test"), true);
  assert.equal(commandLooksLikeFocusedTestCommand("yarn workspaces run test"), false);
  assert.equal(commandLooksLikeTestCommand("npm run test -w api"), true);
  assert.equal(commandLooksLikeBroadTestCommand("npm run test -w api"), false);
  assert.equal(commandLooksLikeFocusedTestCommand("npm run test -w api"), true);
  assert.equal(commandLooksLikeTestCommand("npm run --if-present test -w api"), true);
  assert.equal(commandLooksLikeBroadTestCommand("npm run --if-present test -w api"), false);
  assert.equal(commandLooksLikeFocusedTestCommand("npm run --if-present test -w api"), true);
  assert.equal(commandLooksLikeTestCommand("npm test --workspace api"), true);
  assert.equal(commandLooksLikeBroadTestCommand("npm test --workspace api"), false);
  assert.equal(commandLooksLikeFocusedTestCommand("npm test --workspace api"), true);
  assert.equal(commandLooksLikeTestCommand("npm -w api test"), true);
  assert.equal(commandLooksLikeFocusedTestCommand("npm -w api test"), true);
  assert.equal(commandLooksLikeTestCommand("npm --prefix services/api test"), true);
  assert.equal(commandLooksLikeBroadTestCommand("npm --prefix services/api test"), false);
  assert.equal(commandLooksLikeFocusedTestCommand("npm --prefix services/api test"), true);

  assert.equal(commandLooksLikeTestCommand("pnpm run build"), false);
  assert.equal(commandLooksLikeBroadTestCommand("pnpm run build"), false);
  assert.equal(commandLooksLikeFocusedTestCommand("pnpm run build"), false);
  assert.equal(commandLooksLikeLocalValidationCommand("pnpm run build"), true);
  assert.equal(commandLooksLikeLocalValidationCommand("pnpm --filter api build"), true);
  assert.equal(commandLooksLikeLocalValidationCommand("pnpm exec vitest"), true);
  assert.equal(commandLooksLikeLocalValidationCommand("pnpm run start"), false);
});
