// review-surfaces.ARCH.6: the diagram-label sanitizer is shared — one
// copy in diagrams.ts, imported by every mermaid emitter.
import { diagramLabel, validateMermaidDiagramArtifact } from "./diagrams";
import type {
  PrAffectedArea,
  PrAffectedRequirement,
  PrChangeDiagramModel,
  PrRiskCandidate,
  PrRiskModel,
  PrScopeModel,
  ScopedChangedFile
} from "../pr/contract";

// PR-specific Mermaid change-impact diagram. ONE `flowchart LR` showing the
// path from changed files -> affected areas -> affected requirements -> risk
// candidates, so a reviewer can see at a glance which files pull in which
// requirements and which risks fall out of them.
//
// Determinism: scope/risks are iterated in their existing (already-sorted)
// order; any LOCAL ordering uses compareStrings (never localeCompare). Node ids
// are generated by code (F0/F1, A_<key>, R_<idx>, K_<idx>) and labels are
// sanitized so a path/title can never unbalance Mermaid syntax. No clocks, no
// randomness.

export interface BuildPrChangeDiagramInput {
  scope: PrScopeModel;
  risks: PrRiskModel;
  maxFiles?: number;
  maxRequirements?: number;
  maxRisks?: number;
}

const DIAGRAM_PATH = "diagrams/pr-change-impact.mmd";
const DEFAULT_MAX_FILES = 12;
const DEFAULT_MAX_REQUIREMENTS = 12;
const DEFAULT_MAX_RISKS = 8;


// Node ids are emitted verbatim into Mermaid, so they must be identifier-safe.
// Replace any non [A-Za-z0-9_] run with "_" so group keys like "CLUSTER:SRC/API"
// or "SUB-CLI" cannot inject characters that break the graph.
function safeIdToken(value: string): string {
  return value.replace(/[^A-Za-z0-9_]+/g, "_");
}

interface DiagramNode {
  id: string;
  label: string;
}

// A node line: ID["sanitized label"]. The label has already been stripped of the
// bracket/quote family, so the wrapping ["..."] is always balanced.
function nodeLine(node: DiagramNode): string {
  return `  ${node.id}["${node.label}"]`;
}

function edgeLine(from: string, to: string): string {
  return `  ${from} --> ${to}`;
}

// A risk references a file when any of its evidence refs points at that path.
function riskReferencesPath(risk: PrRiskCandidate, path: string): boolean {
  return risk.evidence.some((ref) => ref.path === path);
}

function riskReferencesAnyPath(risk: PrRiskCandidate, paths: Set<string>): boolean {
  return risk.evidence.some((ref) => typeof ref.path === "string" && paths.has(ref.path));
}

export function buildPrChangeDiagram(input: BuildPrChangeDiagramInput): PrChangeDiagramModel {
  const maxFiles = positiveCap(input.maxFiles, DEFAULT_MAX_FILES);
  const maxRequirements = positiveCap(input.maxRequirements, DEFAULT_MAX_REQUIREMENTS);
  const maxRisks = positiveCap(input.maxRisks, DEFAULT_MAX_RISKS);

  const body = renderBody(input, maxFiles, maxRequirements, maxRisks);
  const validation = validateMermaidDiagramArtifact({ path: DIAGRAM_PATH, body });

  return {
    path: DIAGRAM_PATH,
    status: validation.status,
    body,
    warnings: validation.warnings
  };
}

function positiveCap(value: number | undefined, fallback: number): number {
  if (typeof value === "number" && Number.isFinite(value) && value > 0) {
    return Math.floor(value);
  }
  return fallback;
}

function renderBody(
  input: BuildPrChangeDiagramInput,
  maxFiles: number,
  maxRequirements: number,
  maxRisks: number
): string {
  const { scope, risks } = input;

  // Empty scope: a minimal, valid flowchart with a single explanatory node and a
  // self-describing edge so it satisfies the "flowchart must have an edge" rule.
  if (scope.changed_files.length === 0) {
    return [
      "flowchart LR",
      '  EMPTY["No mapped changes"]',
      '  LEGEND["PR change impact"]',
      "  LEGEND --> EMPTY",
      ""
    ].join("\n");
  }

  const lines: string[] = ["flowchart LR"];
  const edges: string[] = [];

  // --- Files (iterate scope order; cap with a single overflow node) ----------
  const fileNodeByPath = new Map<string, string>();
  const shownFiles = scope.changed_files.slice(0, maxFiles);
  const overflowFiles = scope.changed_files.length - shownFiles.length;
  shownFiles.forEach((file, index) => {
    const id = `F${index}`;
    fileNodeByPath.set(file.path, id);
    lines.push(nodeLine({ id, label: fileLabel(file) }));
  });
  let filesMoreId: string | undefined;
  if (overflowFiles > 0) {
    filesMoreId = "F_MORE";
    lines.push(nodeLine({ id: filesMoreId, label: `... ${overflowFiles} more files` }));
  }

  // --- Areas (iterate scope order; only areas that own a SHOWN file) ---------
  const areaNodeByKey = new Map<string, string>();
  const shownAreas: PrAffectedArea[] = [];
  for (const area of scope.affected_areas) {
    if (area.changed_files.some((path) => fileNodeByPath.has(path))) {
      shownAreas.push(area);
    }
  }
  // safeIdToken collapses any non-[A-Za-z0-9_] run to "_", so two distinct
  // group_keys differing only in punctuation (e.g. "CLUSTER:SRC/API" vs
  // "CLUSTER-SRC-API") would otherwise emit the SAME node id and collide. Track
  // used ids and disambiguate deterministically (shownAreas is already sorted).
  const usedAreaIds = new Set<string>();
  shownAreas.forEach((area) => {
    const base = `A_${safeIdToken(area.group_key)}`;
    let id = base;
    let suffix = 2;
    while (usedAreaIds.has(id)) {
      id = `${base}_${suffix}`;
      suffix += 1;
    }
    usedAreaIds.add(id);
    areaNodeByKey.set(area.group_key, id);
    lines.push(nodeLine({ id, label: areaLabel(area) }));
  });

  // file -> area(s) it belongs to.
  for (const area of shownAreas) {
    const areaId = areaNodeByKey.get(area.group_key);
    if (!areaId) {
      continue;
    }
    for (const filePath of area.changed_files) {
      const fileId = fileNodeByPath.get(filePath);
      if (fileId) {
        edges.push(edgeLine(fileId, areaId));
      }
    }
  }

  // --- Requirements (iterate scope order; cap with a single overflow node) ---
  const reqNodeByIndex = new Map<number, string>();
  const reqNodeById = new Map<string, string>();
  const shownReqs = scope.affected_requirements.slice(0, maxRequirements);
  const overflowReqs = scope.affected_requirements.length - shownReqs.length;
  shownReqs.forEach((req, index) => {
    const id = `R_${index}`;
    reqNodeByIndex.set(index, id);
    reqNodeById.set(req.requirement_id, id);
    lines.push(nodeLine({ id, label: requirementLabel(req) }));
  });
  let reqsMoreId: string | undefined;
  if (overflowReqs > 0) {
    reqsMoreId = "R_MORE";
    lines.push(nodeLine({ id: reqsMoreId, label: `... ${overflowReqs} more requirements` }));
  }

  // area -> requirement (when the requirement's group matches a shown area), else
  // fall back to file -> requirement via the requirement's reason paths. Without
  // the fallback, any requirement with no group_key (every LLM-derived
  // requirement) or whose group_key matches no shown area would be a FLOATING node
  // with no edge — the diagram validator only checks for >=1 edge graph-wide, so
  // such an orphan ships silently.
  shownReqs.forEach((req, index) => {
    const reqId = reqNodeByIndex.get(index);
    if (!reqId) {
      return;
    }
    let anchored = false;
    if (req.group_key) {
      const areaId = areaNodeByKey.get(req.group_key);
      if (areaId) {
        edges.push(edgeLine(areaId, reqId));
        anchored = true;
      }
    }
    if (!anchored) {
      for (const reason of req.reasons) {
        if (reason.path) {
          const fileId = fileNodeByPath.get(reason.path);
          if (fileId) {
            edges.push(edgeLine(fileId, reqId));
            anchored = true;
          }
        }
      }
    }
  });

  // --- Risk candidates (iterate risks order; cap with a single overflow node) -
  const shownRisks = risks.candidates.slice(0, maxRisks);
  const overflowRisks = risks.candidates.length - shownRisks.length;
  const riskNodeById = new Map<string, string>();
  shownRisks.forEach((risk, index) => {
    const id = `K_${index}`;
    riskNodeById.set(risk.id, id);
    lines.push(nodeLine({ id, label: riskLabel(risk) }));
  });
  let risksMoreId: string | undefined;
  if (overflowRisks > 0) {
    risksMoreId = "K_MORE";
    lines.push(nodeLine({ id: risksMoreId, label: `... ${overflowRisks} more risks` }));
  }

  // requirement/area -> risk candidates whose evidence references their files.
  // Prefer the most specific anchor: a requirement (via its reason paths), else
  // the area (via its changed files). A risk with no resolvable anchor still
  // shows; we connect it from any shown file it references so it is never floating.
  const filesForRequirement = (req: PrAffectedRequirement): Set<string> => {
    const paths = new Set<string>();
    for (const reason of req.reasons) {
      if (reason.path && fileNodeByPath.has(reason.path)) {
        paths.add(reason.path);
      }
    }
    return paths;
  };
  const filesForArea = (area: PrAffectedArea): Set<string> => {
    return new Set(area.changed_files.filter((path) => fileNodeByPath.has(path)));
  };

  shownRisks.forEach((risk) => {
    const riskId = riskNodeById.get(risk.id);
    if (!riskId) {
      return;
    }
    let anchored = false;
    // requirement -> risk
    shownReqs.forEach((req, index) => {
      const reqId = reqNodeByIndex.get(index);
      if (reqId && riskReferencesAnyPath(risk, filesForRequirement(req))) {
        edges.push(edgeLine(reqId, riskId));
        anchored = true;
      }
    });
    // area -> risk
    for (const area of shownAreas) {
      const areaId = areaNodeByKey.get(area.group_key);
      if (areaId && riskReferencesAnyPath(risk, filesForArea(area))) {
        edges.push(edgeLine(areaId, riskId));
        anchored = true;
      }
    }
    // fall back to file -> risk so a referenced-but-unanchored risk is not floating.
    if (!anchored) {
      for (const file of shownFiles) {
        const fileId = fileNodeByPath.get(file.path);
        if (fileId && riskReferencesPath(risk, file.path)) {
          edges.push(edgeLine(fileId, riskId));
          anchored = true;
        }
      }
    }
    // Final fallback for PATHLESS risks (large_diff, failed_or_skipped_test use
    // missing evidence with no path): anchor to the first shown file so the risk is
    // tied to the PR scope rather than rendered as a floating node.
    if (!anchored) {
      const firstFileId = fileNodeByPath.get(shownFiles[0]?.path ?? "");
      if (firstFileId) {
        edges.push(edgeLine(firstFileId, riskId));
      }
    }
  });

  // --- Overflow chain edges (keep overflow nodes connected, never floating) --
  if (filesMoreId) {
    const firstFileId = fileNodeByPath.get(shownFiles[0]?.path ?? "");
    if (firstFileId) {
      edges.push(edgeLine(firstFileId, filesMoreId));
    }
  }
  if (reqsMoreId) {
    // Attach the requirements-overflow node to a shown area when one exists,
    // otherwise to a shown requirement, so it always has an incoming edge.
    const anchor = shownAreas.length > 0 ? areaNodeByKey.get(shownAreas[0].group_key) : reqNodeByIndex.get(0);
    if (anchor) {
      edges.push(edgeLine(anchor, reqsMoreId));
    }
  }
  if (risksMoreId) {
    const anchor =
      reqNodeByIndex.get(0) ??
      (shownAreas.length > 0 ? areaNodeByKey.get(shownAreas[0].group_key) : undefined) ??
      fileNodeByPath.get(shownFiles[0]?.path ?? "");
    if (anchor) {
      edges.push(edgeLine(anchor, risksMoreId));
    }
  }

  // De-duplicate edges (a file can belong to several areas; a path can recur)
  // while preserving first-seen order for byte-stability.
  const seen = new Set<string>();
  const dedupedEdges: string[] = [];
  for (const edge of edges) {
    if (!seen.has(edge)) {
      seen.add(edge);
      dedupedEdges.push(edge);
    }
  }

  // Guarantee at least one edge so the flowchart validator accepts the body even
  // in degenerate cases (e.g. a single file in no area with no requirements/risks).
  if (dedupedEdges.length === 0) {
    const firstFileId = fileNodeByPath.get(shownFiles[0]?.path ?? "") ?? "F0";
    lines.push('  SCOPE["PR change impact"]');
    dedupedEdges.push(edgeLine("SCOPE", firstFileId));
  }

  return [...lines, ...dedupedEdges, ""].join("\n");
}

function fileLabel(file: ScopedChangedFile): string {
  const status = diagramLabel(file.status);
  const path = diagramLabel(file.path);
  return status ? `${path} (${status})` : path;
}

function areaLabel(area: PrAffectedArea): string {
  const name = diagramLabel(area.name || area.group_key);
  return name || diagramLabel(area.group_key) || "area";
}

function requirementLabel(req: PrAffectedRequirement): string {
  const id = diagramLabel(req.acai_id ?? req.requirement_id);
  const title = req.title ? diagramLabel(req.title) : "";
  return title ? `${id}: ${title}` : id || "requirement";
}

function riskLabel(risk: PrRiskCandidate): string {
  const id = diagramLabel(risk.id);
  const summary = diagramLabel(risk.summary);
  return summary ? `${id}: ${summary}` : id || "risk";
}
